specVersion: 0.2.0
name: acala-loans
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  endpoint: wss://karura.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/AcalaNetwork/karura-dictionary
  chaintypes:
    file: './src/types.json'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleMinted 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: Minted
        - handler: handleRequestedRedeem 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RequestedRedeem
        - handler: handleRequestedCancelled 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RequestedCancelled
        - handler: handleRedeemedByFastMatch 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RedeemedByFastMatch
        - handler: handleRedeemedByUnbond 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RedeemedByUnbond
        - handler: handleWithdrawRedemption 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: WithdrawRedemption