specVersion: 0.2.0
name: acala-homa
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xdbfe6ec93682a8441a55ca06a251da42a36eaedc9deeb4cc290de6a3beab3c66'
  endpoint: wss://kusama-1.polkawallet.io:3000
  chaintypes:
    file: './src/types.json'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleMinted 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: Minted
        - handler: handleRequestedRedeem 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RequestedRedeem
        - handler: handleRequestedCancelled 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RequestedCancelled
        - handler: handleRedeemedByFastMatch 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RedeemedByFastMatch
        - handler: handleRedeemedByUnbond 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: RedeemedByUnbond
        - handler: handleWithdrawRedemption 
          kind: substrate/EventHandler
          filter:
            module: homa 
            method: WithdrawRedemption
